branch TrueConstant  := 'true'
branch FalseConstant := 'false'
branch NullConstant  := 'null'
group  Constant      := Integer | String | TrueConstant | FalseConstant | NullConstant

group  Atom          := Variable | Constant

branch VarKeyPair    := <Variable as key> ':' <ExpressionValue>
branch StrKeyPair    := <String as key> ':' <ExpressionValue>
group  KeyPair       := VarKeyPair | StrKeyPair

branch List          := '[' <CS>.<Expression in items> ']'
branch Dict          := '{' <CS>.<KeyPair in items> '}'
branch Call          := <Primary as obj> '(' <CS>.<Expression in args> ')'
group  Primary       := List | Dict | Constant

branch Append        := <Primary as obj> '.' 'append' '(' <Expression as item> ')'
branch Length        := <Primary as obj> '.' 'length' '(' ')'
group  Secondary     := Append | Length | Primary

branch Mul           := <Term as left> <S> '*' <S> <Secondary as right>
branch Div           := <Term as left> <S> '/' <S> <Secondary as right>
group  Term          := Mul | Div | Secondary

branch Add           := <Sum as left> <S> '+' <S> <Term as right>
branch Sub           := <Sum as left> <S> '-' <S> <Term as right>
group  Sum           := Add | Sub | Term

branch Eq            := <Sum as left> <S> '==' <S> <Sum as right>
branch In            := <Sum as left> <S> 'in' <S> <Sum as right>
group  Comparison    := Eq | In | Sum

group  Expression    := Comparison