keyword[200] Null 'null'
keyword[200] TrueValue 'true'
keyword[200] FalseValue 'false'
regex[100] Integer '\-?\d+'
regex[100] String '".*?"'
string[100] NEWLINE '\n' ignore
regex[0] WHITESPACE '[\t\r ]+' ignore

group  ItemGR := String | Integer | TrueValue | FalseValue | Null | NestedGR

branch Pair := <String as key> ':' $' ' <ItemGR as val>
branch Dict := '{' [',' $' '].<Pair in items> '}'
branch List := '[' [',' $' '].<ItemGR in items> ']'
group  NestedGR := Dict | List

group  CodeGR := ItemGR | Pair

>NestedGR