regex Variable '[a-zA-Z]\w*'
regex WHITESPACE '[ \t\n\r]+' ignore
string CreateImports '-i'
string ParamRepeat '-r'
string ParamDebug '-d'

alias S := $' '

branch TargetList   := <S>..<Variable in items>
branch All          := '*'
group  TargetListGR := TargetList | All | Variable

branch Quit     := 'quit'
branch Help     := 'help'
branch Scan     := 'scan' ?[<S> <ParamDebug as debug>]
branch Open     := 'open' <S> <Variable as repo>
branch Test     := 'test' <S> <TargetListGR as target>
branch Create   := 'create' <S> <Variable as target> ?[<S> <CreateImports as create_imports>] # TODO : add create config parameters
branch Update   := 'update' <S> <TargetListGR as target> ?[<S> <ParamRepeat as repeat_>]
group  Command  := Quit | Help | Scan | Open | Test | Create | Update

branch CommandList   := [<S> '&' <S>]..<Command in commands>
group  CommandListGR := CommandList | Command

group  Generic  := CommandListGR | TargetListGR | CreateImports | ParamRepeat | ParamDebug

> CommandListGR