# références :
# -> https://docs.python.org/3/reference/grammar.html

regex Variable '[a-zA-Z]\w*'
regex Integer '\d+'
regex Float '\d+\.\d*|\.\d+'
regex Comment '#.*'
regex MultiLineString '\"\"\".*?\"\"\"' 16
regex String '\"(?:\"|[^\"])*?(?<!\\\\)\"|\'(?:\'|[^\'])*?(?<!\\\\)\''
regex WHITESPACE '[ \t\n\r]+' ignore